# Generated by Django 2.0 on 2018-03-19 02:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('newsoutlet', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=200)),
                ('date_joined', models.DateField()),
                ('text', models.CharField(max_length=100)),
                ('polarity', models.CharField(max_length=4)),
                ('subjectivity', models.CharField(max_length=4)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, size=None)),
            ],
        ),
    ]
