# Generated by Django 2.0 on 2018-03-24 01:39

import HerokuNewsApp.models
import django.contrib.postgres.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HerokuNewsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlescheme',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=HerokuNewsApp.models.TruncatingCharField(max_length=10), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='articlescheme',
            name='newsoutlet',
            field=HerokuNewsApp.models.TruncatingCharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='articlescheme',
            name='polarity',
            field=HerokuNewsApp.models.TruncatingCharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='articlescheme',
            name='subjectivity',
            field=HerokuNewsApp.models.TruncatingCharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='articlescheme',
            name='text',
            field=HerokuNewsApp.models.TruncatingCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='articlescheme',
            name='title',
            field=HerokuNewsApp.models.TruncatingCharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='articlescheme',
            name='url',
            field=HerokuNewsApp.models.TruncatingCharField(max_length=200),
        ),
    ]
